import type { MobileTextKey, MobileTranslate } from "@openbot/i18n/mobile";

// Hermes has no Intl.DisplayNames, so the dictation language picker names
// locales from catalog keys. They cover the languages and regions that the iOS
// and Google speech recognizers list. A code missing here shows as the code.

const LANGUAGES: Record<string, MobileTextKey> = {
  af: "language.name.af",
  am: "language.name.am",
  ar: "language.name.ar",
  az: "language.name.az",
  be: "language.name.be",
  bg: "language.name.bg",
  bn: "language.name.bn",
  bs: "language.name.bs",
  ca: "language.name.ca",
  cs: "language.name.cs",
  cy: "language.name.cy",
  da: "language.name.da",
  de: "language.name.de",
  el: "language.name.el",
  en: "language.name.en",
  es: "language.name.es",
  et: "language.name.et",
  eu: "language.name.eu",
  fa: "language.name.fa",
  fi: "language.name.fi",
  fil: "language.name.fil",
  fr: "language.name.fr",
  ga: "language.name.ga",
  gl: "language.name.gl",
  gu: "language.name.gu",
  he: "language.name.he",
  hi: "language.name.hi",
  hr: "language.name.hr",
  hu: "language.name.hu",
  hy: "language.name.hy",
  id: "language.name.id",
  is: "language.name.is",
  it: "language.name.it",
  iw: "language.name.he",
  ja: "language.name.ja",
  jv: "language.name.jv",
  ka: "language.name.ka",
  kk: "language.name.kk",
  km: "language.name.km",
  kn: "language.name.kn",
  ko: "language.name.ko",
  lo: "language.name.lo",
  lt: "language.name.lt",
  lv: "language.name.lv",
  mk: "language.name.mk",
  ml: "language.name.ml",
  mn: "language.name.mn",
  mr: "language.name.mr",
  ms: "language.name.ms",
  my: "language.name.my",
  nb: "language.name.nb",
  ne: "language.name.ne",
  nl: "language.name.nl",
  no: "language.name.no",
  pa: "language.name.pa",
  pl: "language.name.pl",
  pt: "language.name.pt",
  ro: "language.name.ro",
  ru: "language.name.ru",
  si: "language.name.si",
  sk: "language.name.sk",
  sl: "language.name.sl",
  sq: "language.name.sq",
  sr: "language.name.sr",
  su: "language.name.su",
  sv: "language.name.sv",
  sw: "language.name.sw",
  ta: "language.name.ta",
  te: "language.name.te",
  th: "language.name.th",
  tl: "language.name.fil",
  tr: "language.name.tr",
  uk: "language.name.uk",
  ur: "language.name.ur",
  uz: "language.name.uz",
  vi: "language.name.vi",
  wuu: "language.name.wuu",
  yue: "language.name.yue",
  zh: "language.name.zh",
  zu: "language.name.zu",
};

const REGIONS: Record<string, MobileTextKey> = {
  "419": "language.region.419",
  AE: "language.region.ae",
  AL: "language.region.al",
  AM: "language.region.am",
  AR: "language.region.ar",
  AT: "language.region.at",
  AU: "language.region.au",
  AZ: "language.region.az",
  BA: "language.region.ba",
  BD: "language.region.bd",
  BE: "language.region.be",
  BG: "language.region.bg",
  BH: "language.region.bh",
  BO: "language.region.bo",
  BR: "language.region.br",
  BY: "language.region.by",
  CA: "language.region.ca",
  CH: "language.region.ch",
  CL: "language.region.cl",
  CN: "language.region.cn",
  CO: "language.region.co",
  CR: "language.region.cr",
  CU: "language.region.cu",
  CZ: "language.region.cz",
  DE: "language.region.de",
  DK: "language.region.dk",
  DO: "language.region.do",
  DZ: "language.region.dz",
  EC: "language.region.ec",
  EE: "language.region.ee",
  EG: "language.region.eg",
  ES: "language.region.es",
  ET: "language.region.et",
  FI: "language.region.fi",
  FR: "language.region.fr",
  GB: "language.region.gb",
  GE: "language.region.ge",
  GH: "language.region.gh",
  GR: "language.region.gr",
  GT: "language.region.gt",
  HK: "language.region.hk",
  HN: "language.region.hn",
  HR: "language.region.hr",
  HU: "language.region.hu",
  ID: "language.region.id",
  IE: "language.region.ie",
  IL: "language.region.il",
  IN: "language.region.in",
  IQ: "language.region.iq",
  IR: "language.region.ir",
  IS: "language.region.is",
  IT: "language.region.it",
  JO: "language.region.jo",
  JP: "language.region.jp",
  KE: "language.region.ke",
  KH: "language.region.kh",
  KR: "language.region.kr",
  KW: "language.region.kw",
  KZ: "language.region.kz",
  LA: "language.region.la",
  LB: "language.region.lb",
  LK: "language.region.lk",
  LT: "language.region.lt",
  LV: "language.region.lv",
  MA: "language.region.ma",
  MK: "language.region.mk",
  MM: "language.region.mm",
  MN: "language.region.mn",
  MO: "language.region.mo",
  MX: "language.region.mx",
  MY: "language.region.my",
  NG: "language.region.ng",
  NI: "language.region.ni",
  NL: "language.region.nl",
  NO: "language.region.no",
  NP: "language.region.np",
  NZ: "language.region.nz",
  OM: "language.region.om",
  PA: "language.region.pa",
  PE: "language.region.pe",
  PH: "language.region.ph",
  PK: "language.region.pk",
  PL: "language.region.pl",
  PR: "language.region.pr",
  PS: "language.region.ps",
  PT: "language.region.pt",
  PY: "language.region.py",
  QA: "language.region.qa",
  RO: "language.region.ro",
  RS: "language.region.rs",
  RU: "language.region.ru",
  SA: "language.region.sa",
  SE: "language.region.se",
  SG: "language.region.sg",
  SI: "language.region.si",
  SK: "language.region.sk",
  SV: "language.region.sv",
  TH: "language.region.th",
  TN: "language.region.tn",
  TR: "language.region.tr",
  TW: "language.region.tw",
  TZ: "language.region.tz",
  UA: "language.region.ua",
  UG: "language.region.ug",
  US: "language.region.us",
  UY: "language.region.uy",
  UZ: "language.region.uz",
  VE: "language.region.ve",
  VN: "language.region.vn",
  YE: "language.region.ye",
  ZA: "language.region.za",
};

/** "pl-PL" becomes "Polish (Poland)". A script subtag, such as "Hans", is skipped. */
export function localeName(locale: string, t: MobileTranslate): string | null {
  const [language, ...rest] = locale.replace(/_/g, "-").split("-");
  const languageKey = language ? LANGUAGES[language.toLowerCase()] : undefined;
  if (!languageKey) return null;
  const region = rest.find((part) => /^([A-Za-z]{2}|\d{3})$/.test(part));
  if (!region) return t(languageKey);
  const regionKey = REGIONS[region.toUpperCase()];
  return t("language.withRegion", {
    language: t(languageKey),
    region: regionKey ? t(regionKey) : region.toUpperCase(),
  });
}
