import type { ConversationProps } from "./conversation-types";

export function testConversationProps(agentId: string): ConversationProps {
  return {
    agentStatus: {
      phase: "ready",
      cliVersion: null,
      auth: { kind: "unknown" },
      capabilities: { chat: "ready", browser: "ready", computerUse: "ready" },
      message: null,
      fullAccess: true,
    },
    agent: {
      id: agentId,
      name: "Test agent",
      title: "",
      description: "",
      notifications: false,
      provider: "codex",
      model: "gpt-5.6-luna",
      reasoningEffort: "medium",
      threadId: null,
      avatarSeed: "seed",
      avatarHue: null,
      avatarUrl: null,
      time: "",
      preview: "",
    },
    agents: [],
    modelOptions: [],
    messages: [],
    unreadCount: 0,
    firstUnreadMessageId: null,
    loaded: true,
    activeTurnId: null,
    globalOverlayOpen: false,
    settingsRequest: null,
    messageFocusRequest: null,
    queue: undefined,
    browserTabs: [],
    activeBrowserTabId: null,
    browserVisibilitySuspended: false,
    browserControlState: { sessions: [] },
    server: undefined,
    presence: { serverId: null, members: [], updatedAt: "" },
    currentUserEmail: "",
    remoteDesktopSessionActive: false,
    remoteDesktopVisible: false,
    prompt: undefined,
    approval: undefined,
    browserTakeover: undefined,
    onSelectAgent: () => {},
    onUpdateAgent: async () => {},
    onSetAgentAvatar: async () => {},
    onSendMessage: async () => true,
    onMarkRead: async () => {},
    onTypingChange: () => {},
    onAnswerPrompt: async () => true,
    onRespondToApproval: async () => true,
    onRespondToBrowserTakeover: async () => true,
    onCancelQueuedMessage: () => {},
    onSteerQueuedMessage: () => {},
    onUpdateQueuedMessage: async () => true,
    onReorderQueue: () => {},
    onActivateBrowserTab: () => {},
    onCloseBrowserTab: () => {},
    onOpenRemoteDesktop: async () => {},
    onStop: () => {},
  };
}
